# Generated by Django 3.1.7 on 2021-10-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=200)),
                ('celular', models.CharField(max_length=11)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
    ]
