# Generated by Django 3.1.7 on 2021-10-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ganaderia', '0002_auto_20211023_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.IntegerField(choices=[(1, 'Abeja'), (2, 'Caballo'), (3, 'Cabra'), (4, 'Cerdo'), (5, 'Conejo'), (6, 'Gallina'), (7, 'Gallo'), (8, 'Obeja'), (9, 'Pato'), (10, 'pez'), (11, 'Toro'), (12, 'Vaca')], default='Animal')),
                ('Anos', models.CharField(max_length=2)),
                ('Sexo', models.IntegerField(choices=[(1, 'Macho'), (2, 'Hembra')], default='Genero')),
            ],
        ),
    ]
