# Generated by Django 3.1.7 on 2021-10-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ganaderia', '0003_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='animal',
            field=models.CharField(choices=[('Abeja', 'Abeja'), ('Caballo', 'Caballo'), ('Cabra', 'Cabra'), ('Cerdo', 'Cerdo'), ('Conejo', 'Conejo'), ('Gallina', 'Gallina'), ('Gallo', 'Gallo'), ('Obeja', 'Obeja'), ('Pato', 'Pato'), ('pez', 'pez'), ('Toro', 'Toro'), ('Vaca', 'Vaca')], default='Animal', max_length=10),
        ),
    ]
