# Generated by Django 3.1.7 on 2021-10-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ganaderia', '0004_auto_20211025_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
